PATCH http://localhost:5038/User
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJKV1RTZXJ2aWNlQWNjZXNzVG9rZW4iLCJqdGkiOiJhYTg0ZTNkYy0yMmIxLTQ2MDctOWU1MS0xZTUwZjllYmU2NTIiLCJpYXQiOiIwMy8xMS8yMDIzIDA5LjQ3LjQ2IiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZSI6ImFkbWluIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiYWRtaW4iLCJleHAiOjE2OTkwMDg0NjYsImlzcyI6IkpXVEF1dGhlbnRpY2F0aW9uU2VydmVyIiwiYXVkIjoiSldUU2VydmljZUJsYXpvcldhc21DbGllbnQifQ.dm9wCw6BtK7jwQ11DPaWvMlyzvqIz5w1DHFH8R1u517mUNbeT1DdAAwr4AeCaFQRh8q1TsmMEcCYoggoFLGtdw
Content-Type: application/json

{ "username": "maja", "role": "user" }






