GET http://localhost:5038/Test/isUser
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJKV1RTZXJ2aWNlQWNjZXNzVG9rZW4iLCJqdGkiOiJiNTZjMjgyYS1jZjY4LTRhN2UtODQ2NS05ZTY0ODJiMDQwMzUiLCJpYXQiOiIwMy8xMS8yMDIzIDA4LjQxLjI5IiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZSI6ImFkbWluIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiYWRtaW4iLCJleHAiOjE2OTkwMDQ0ODksImlzcyI6IkpXVEF1dGhlbnRpY2F0aW9uU2VydmVyIiwiYXVkIjoiSldUU2VydmljZUJsYXpvcldhc21DbGllbnQifQ.YQr_SKS9PF95Gw20tZaZVb5fcgMirUc1jx7qxRRgBbKzGQmrKQUdnME7h15zJ8gC7mK96F7a4tMOHdRDU3Fx6w







